CMS.Admin/Models/DVC_QuyenLienQuan/DVC_QuyenLienQuanViewModel.cs
using Business.Entities.Domain;
using PagedList;

namespace CMS.Admin.Models
{
    public class DVC_QuyenLienQuanViewModel
    {
        public DVC_QLQ_QuyenLienQuanParam Search { get; set; }
        public IPagedList<DVC_QLQ_QuyenLienQuanMap> List { get; set; }
    }
}

CMS.Admin/Controllers/DVC_QuyenLienQuanController.cs
using Business.Entities.Domain;
using CMS.Admin.Common;
using CMS.Admin.Constaints;
using CMS.Admin.Models;
using Core.Common.Utilities;
using Module.Framework;
using Module.Framework.Common;
using Module.Framework.Utilities;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Configuration;
using System.Web.Mvc;

namespace CMS.Admin.Controllers
{
    public class DVC_QuyenLienQuanController : BaseController
    {
        private int _pageSize;
        private Guid _nguoiDungID;
        private long _userPortalID;
        private string _userFullName;
        public DVC_QuyenLienQuanController()
        {
            var pageSize = DungChung.GetKeyCauHinhHeThong("SoHangHienThi");
            if (!int.TryParse(pageSize, out this._pageSize))
                this._pageSize = 10;
            _nguoiDungID = LoginManager.GetCurrentUser() != null ? Guid.Parse(LoginManager.GetCurrentUser().UserId) : Guid.Empty;
            _userPortalID = LoginManager.GetCurrentUser() != null ? LoginManager.GetCurrentUser().UserPortalID : 0;
            _userFullName = LoginManager.GetCurrentUser() != null ? LoginManager.GetCurrentUser().UserFullName : "";
        }

        #region QuyenLienQuan
        [CustomAuthorize(RightName = CookieRight.DVC_QuyenLienQuan_Index)]
        public ActionResult Index()
        {
            if (DungChung.CheckTimeDN() == false)
            {
                return RedirectToAction("LogOff", "NguoiDungHeThong");
            }
            var result = new DVC_QuyenLienQuanViewModel();
            result.Search = new DVC_QLQ_QuyenLienQuanParam();
            try
            {
                result.Search.PageSize = this._pageSize;
                result.Search.PageIndex = 1;
                using (var _quyenLienQuanSVR = new DVC_QuyenLienQuanServiceClient())
                {
                    var tempList = _quyenLienQuanSVR.DVC_QLQ_QuyenLienQuan_List(result.Search);
                    if (tempList.Data != null && tempList.Data.resultObject != null && tempList.Data.resultObject.Any())
                    {
                        DungChung.ghinhatkynguoidung("Xem danh sách quyền liên quan",
                                               "DVC_QuyenLienQuanController",
                                               "Index", "View");
                        result.List = tempList.Data.resultObject.ToPagedList(1, result.Search.PageSize);
                    }
                }
                return View(result);
            }
            catch (Exception ex)
            {
                DungChung.ghiloghethong("DVC_QuyenLienQuanController/Index error:" + ex.Message, ex, Request);
                return View(result);
            }
        }

        [HttpPost]
        public ActionResult Index(DVC_QLQ_QuyenLienQuanParam model)
        {
            if (DungChung.CheckTimeDN() == false)
            {
                return RedirectToAction("LogOff", "NguoiDungHeThong");
            }
            var result = new DVC_QuyenLienQuanViewModel();
            try
            {
                //model.PageSize = this._pageSize;
                using (var _quyenLienQuanSVR = new DVC_QuyenLienQuanServiceClient())
                {
                    var tempList = _quyenLienQuanSVR.DVC_QLQ_QuyenLienQuan_List(model);
                    if (tempList.Data != null && tempList.Data.resultObject != null && tempList.Data.resultObject.Any())
                    {
                        DungChung.ghinhatkynguoidung("Xem danh sách quyền liên quan",
                                               "DVC_QuyenLienQuanController",
                                               "Index", "View");
                        result.List = tempList.Data.resultObject.ToPagedList(1, model.PageSize);
                    }
                }
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_IndexPartialView", result);
                }
                return View(result);
            }
            catch (Exception ex)
            {
                DungChung.ghiloghethong("DVC_QuyenLienQuanController/Index error:" + ex.Message, ex, Request);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_IndexPartialView", result);
                }
                return View(result);
            }
        }

        [CustomAuthorize]
        [CustomAuthorize(RightName = CookieRight.DVC_QuyenLienQuan_InsUpd)]
        public ActionResult Insert(string id)
        {
            if (DungChung.CheckTimeDN() == false)
            {
                return RedirectToAction("LogOff", "NguoiDungHeThong");
            }
            var result = new DVC_QLQ_QuyenLienQuanAdd();
            result.LoaiDangKyID = 2;
            result.HinhDaiDienStt = -1;
            result.PhimStt = -1;
            result.NgayCap = DateTime.Today.ToString("dd/MM/yyyy");
            try
            {
                ViewBag.TieuDe = "Cấp giấy chứng nhận đăng ký quyền liên quan - Nhập tác phẩm";
                if (id != "" && id != null)
                {
                    using (var _quyenLienQuanSVR = new DVC_QuyenLienQuanServiceClient())
                    {
                        var tempList = _quyenLienQuanSVR.DVC_QLQ_QuyenLienQuan_ById(long.Parse(id));
                        if (tempList != null && tempList.Data != null && tempList.Data.resultObject != null)
                        {
                            result = tempList.Data.resultObject;
                        }
                    }
                }
                result.UserFullName = _userFullName;
                return View(result);
            }
            catch (Exception ex)
            {
                DungChung.ghiloghethong("DVC_QuyenLienQuanController/Insert error:" + ex.Message, ex, Request);
                return View(result);
            }
        }

        [HttpPost]
        public ActionResult CapSo(long id, int loaiNghiepVuID)
        {
            if (DungChung.CheckTimeDN() == false)
            {
                return RedirectToAction("LogOff", "NguoiDungHeThong");
            }
            bool status = false; string stt = ""; string soGCN = "";
            try
            {
                using (var _capSoSVR = new HS_CapSoServiceClient())
                {
                    var tempList = _capSoSVR.DVC_HS_CapSo_GenSo(2);
                    if (tempList.Data != null && tempList.Data.resultObject != null)
                    {
                        status = true; stt = tempList.Data.resultObject.STT; soGCN = tempList.Data.resultObject.SoGCN;
                    }
                }
                return Json(new { status = status, id = id, stt = stt, soGCN = soGCN });
            }
            catch (Exception ex)
            {
                DungChung.ghiloghethong("DVC_QuyenLienQuanController/CapSo error:" + ex.Message, ex, Request);
                return Json(new { status = status });
            }
        }

        [HttpPost]
        [CustomAuthorize(RightName = CookieRight.DVC_QuyenLienQuan_InsUpd)]
        [CheckForAntiForgeryToken]
        public ActionResult SaveQuyenLienQuan()
        {
            if (DungChung.CheckTimeDN() == false)
            {
                return RedirectToAction("LogOff", "NguoiDungHeThong");
            }
            bool status = false; long id = 0; bool checkSoGCN = false; bool checkSoTT = false;
            try
            {
                var model = ColectionItem<DVC_QLQ_QuyenLienQuanAdd>("modelThongTin");
                if (model != null)
                {
                    model.UserID = _nguoiDungID;
                    using (var _quyenLienQuanSVR = new DVC_QuyenLienQuanServiceClient())
                    {
                        var ckSoTT = _quyenLienQuanSVR.DVC_QLQ_QuyenLienQuan_CheckSoTT(model.QuyenLienQuanID, model.STT);
                        if (ckSoTT != null && ckSoTT.Data != null && ckSoTT.Data.resultObject > 0)
                        {
                            checkSoTT = true;
                            var ckSoGCN = _quyenLienQuanSVR.DVC_QLQ_QuyenLienQuan_CheckSoGCN(model.QuyenLienQuanID, model.SoGCN);
                            if (ckSoGCN != null && ckSoGCN.Data != null && ckSoGCN.Data.resultObject > 0)
                            {
                                checkSoGCN = true;
                                var tempList = _quyenLienQuanSVR.DVC_QLQ_QuyenLienQuan_InsUpd(model);
                                if (tempList.Data != null && tempList.Data.resultObject > 0)
                                {
                                    DungChung.ghinhatkynguoidung("Thêm mới quyền liên quan",
                                                     "DVC_QuyenLienQuanController",
                                                     "SaveQuyenLienQuan", "Create");
                                    status = true; id = tempList.Data.resultObject;
                                }
                            }
                        }
                    }
                }
                return Json(new { checkSoTT = checkSoTT, checkSoGCN = checkSoGCN, status = status, data = id });
            }
            catch (Exception ex)
            {
                DungChung.ghiloghethong("DVC_QuyenLienQuanController/SaveQuyenLienQuan error:" + ex.Message, ex, Request);
                return Json(new { status = status });
            }
        }

        [HttpPost]
        public ActionResult DeleteQuyenLienQuan(long id)
        {
            if (DungChung.CheckTimeDN() == false)
            {
                return RedirectToAction("LogOff", "NguoiDungHeThong");
            }
            bool status = false;
            try
            {
                if (id > 0)
                {
                    using (var _quyenLienQuanSVR = new DVC_QuyenLienQuanServiceClient())

CMS.Admin/Views/DVC_QuyenLienQuan/DialogSearchCongDan/Index.cshtml
@using Module.Framework.Common;
@{
    var user = LoginManager.GetCurrentUser();
    var admin = LoginManager.CheckAdmin();
    var modelParam = new Business.Entities.Domain.TT_CongDanParam();
    var modelList = new List<Business.Entities.Domain.TT_CongDanMap>();
    var modelAdd = new Business.Entities.Domain.TT_CongDanAdd();
}
<script src="~/Scripts/DVC_QuyenLienQuan/DVC_QuyenLienQuan_SearchCongDan.js"></script>
<div class="modal fade custom-margin-form-group" id="dialogSearchCongDan" aria-hidden="false" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header h-25">
                <h5 class="modal-title">Thông tin công dân </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group sh-search-congdan">
                    @Html.Partial("DialogSearchCongDan/Search", modelParam)
                </div>
                <div class="form-group sh-info-congdan hidden">
                    <form role="form" id="form-update-congdan" class="form-horizontal label-right">
                        @Html.Partial("DialogSearchCongDan/Update", modelAdd)
                    </form>
                </div>
                <div class="table-responsive mt-3" id="result-searchcongdan">
                    @Html.Partial("DialogSearchCongDan/List", modelList)
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success btn-sm" id="btnAddCongDan"><i class="far fa-save mr-1"></i> Chọn</button>
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal"><i class="fas fa-times mr-2"></i> Đóng</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        if (Common.Empty(Common.DVC_QuyenLienQuan_SearchCongDan)) {
            Common.DVC_QuyenLienQuan_SearchCongDan = new DVC_QuyenLienQuan_SearchCongDan({
                Url: {
                    SearchCongDan: '@Url.Action("SearchCongDan", "DVC_QuyenLienQuan")',
                    SaveCongDan: '@Url.Action("SaveCongDan", "DVC_QuyenLienQuan")',
                    UpdateCongDan: '@Url.Action("UpdateCongDan", "DVC_QuyenLienQuan")',
                },
                ListChuSoHuu: [],
                ListNguoiBieuDien: [],
            });
            $("#tableChuSoHuu tbody tr").each(function () {
                if ($(this).closest("tr").data("id") > 0) {
                    Common.DVC_QuyenLienQuan_SearchCongDan.ListChuSoHuu.push({
                        ChuSoHuuID: $(this).closest("tr").data("id"),
                        HoVaTen: $(this).closest("tr").data("name"),
                        QuocTich: $(this).closest("tr").data("country"),
                        SoCMND: $(this).closest("tr").data("cccd"),
                        SoDKKD: $(this).closest("tr").data("dkkd"),
                        DiaChi: $(this).closest("tr").data("address")
                    });
                }
            });
            $("#tableNguoiBieuDien tbody tr").each(function () {
                if ($(this).closest("tr").data("id") > 0) {
                    Common.DVC_QuyenLienQuan_SearchCongDan.ListNguoiBieuDien.push({
                        NguoiBieuDienID: $(this).closest("tr").data("id"),
                        HoVaTen: $(this).closest("tr").data("name"),
                        QuocTich: $(this).closest("tr").data("country"),
                        SoCMND: $(this).closest("tr").data("cccd"),
                        DiaChi: $(this).closest("tr").data("address")
                    });
                }
            });
        }
        else {
            Common.DVC_QuyenLienQuan_SearchCongDan.RegisterEvent();
        }
    });
</script>

CMS.Admin/Views/DVC_QuyenLienQuan/DialogSearchCongDan/List.cshtml
@using Core.Common.Common;
@using Module.Framework.Common;
@using CMS.Admin.Constaints;
@{
    var user = LoginManager.GetCurrentUser();
    var admin = LoginManager.CheckAdmin();

}
@model List<Business.Entities.Domain.TT_CongDanMap>

<table id="table-congdan" cellspacing="0" cellpadding="0" class="table table-hover mb-0 table-striped table-mobile table-bordered">
    <thead>
        <tr class="thead-row bg-info text-white">
            <th class="text-center cursor" width="30">C <input type="checkbox" class="cursor" id="selectAllCheckBoxCSH"></th>
            <th class="text-center cursor" width="30">B <input type="checkbox" class="cursor" id="selectAllCheckBoxNBD"></th>
            <th width="200">Họ và Tên</th>
            <th width="100">Quốc tịch</th>
            <th width="100">CCCD/Hộ chiếu</th>
            <th width="100">Ngày cấp</th>
            <th width="100">ĐKKD</th>
            <th width="100">Ngày cấp ĐKKD</th>
            <th width="100">Bút danh</th>
            <th width="300">Địa chỉ</th>
            <th width="50" class="text-center">Thao tác</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                <tr data-id="@item.CongDanID" data-name="@item.HoVaTen" data-country="@item.QuocTich" data-cccd="@item.SoCMND" data-address="@item.DiaChi" data-dkkd="@item.SoDKKD" data-butdanh="@item.ButDanh" class="trCongDan cursor">
                    <td class="text-center"><input type="checkbox" class="cursor" name="chkInputCheckedCSH[]"></td>
                    <td class="text-center"><input type="checkbox" class="cursor" name="chkInputCheckedNBD[]"></td>
                    <td data-label="Họ và Tên">@Html.Raw(item.HoVaTen ?? "&nbsp;")</td>
                    <td data-label="Quốc tịch">@Html.Raw(item.QuocTich ?? "&nbsp;")</td>
                    <td data-label="CCCD/Hộ chiếu">@Html.Raw(item.SoCMND ?? "&nbsp;")</td>
                    <td data-label="Ngày cấp">@Html.Raw(item.NgayCap ?? "&nbsp;")</td>
                    <td data-label="ĐKKD">@Html.Raw(item.SoDKKD ?? "&nbsp;")</td>
                    <td data-label="Ngày cấp ĐKKD">@Html.Raw(item.NgayCapDKKD ?? "&nbsp;")</td>
                    <td data-label="Bút danh">@Html.Raw(item.ButDanh ?? "&nbsp;")</td>
                    <td data-label="Địa chỉ">@Html.Raw(item.DiaChi ?? "&nbsp;")</td>
                    <td data-label="Thao tác" class="text-center">
                        @if (admin == true || user.Right.Contains(CookieRight.TT_CongDan_InsUpd))
                        {
                            <button title="Chỉnh sửa" data-id="@item.CongDanID" class="btn btn-primary btn-sm btn-update-congdan" type="button"><i class="far fa-edit"></i></button>
                        }
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="11">
                    <div class="alert alert-info mt-3" role="alert">
                        Không có dữ liệu
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (Model != null && Model.Any())
{
    <!--- Pagination -->
    <div class="paging-bottom">
        @Html.Raw(Ajax.Pager(
                new Options
                {
                    PageSize = Model[0].PageSize,
                    TotalItemCount = Model[0].TotalCount,
                    CurrentPage = Model[0].PageIndex,
                    IsShowControls = true,
                    IsShowFirstLast = true,
                    LimitPage = 5,
                    Link = "javascript:void(0);",
                    OnClick = "Common.DVC_QuyenLienQuan_SearchCongDan.Paging({0})",
                    OnChangePageSize = "Common.DVC_QuyenLienQuan_SearchCongDan.ChangePageSize(this)",
                }))
    </div>
    <!--- End Pagination -->
}

CMS.Admin/Views/DVC_QuyenLienQuan/DialogSearchCongDan/Search.cshtml
@using Module.Framework.Common;
@using CMS.Admin.Constaints;
@model Business.Entities.Domain.TT_CongDanParam
@{
    var user = LoginManager.GetCurrentUser();
    var admin = LoginManager.CheckAdmin();
}
@using (Ajax.BeginForm("SearchCongDan", "DVC_QuyenLienQuan", null, new AjaxOptions
{
    HttpMethod = "Post",
    OnBegin = "Common.DVC_QuyenLienQuan_SearchCongDan.BeforeSend",
    OnSuccess = "Common.DVC_QuyenLienQuan_SearchCongDan.Success",
    OnFailure = "Common.ErrorMessage"
}, new { @class = "", @role = "form", @id = "idFormSearchCongDan" }))
{
    <div class="hidden">
        @Html.HiddenFor(m => m.PageIndex)
        @Html.HiddenFor(m => m.PageSize)
    </div>

    <div class="form-row">
        <div class="form-group col-md-4">
            <label class="font-weight-bold">Họ và tên</label>
            @Html.TextBoxFor(m => m.HoVaTen, new { @class = "form-control form-control-sm", @placeholder = "Nhập tên chủ sở hữu", @onchange = "Common.DVC_QuyenLienQuan_SearchCongDan.SubmitForm()", @onkeyup = "Common.DVC_QuyenLienQuan_SearchCongDan.SubmitForm()" })
        </div>
        <div class="form-group col-md-4">
            <label class="font-weight-bold">Số CMNN/Hộ chiếu</label>
            @Html.TextBoxFor(m => m.SoCMND, new { @class = "form-control form-control-sm", @placeholder = "Nhập số CMNN/hộ chiếu", @onchange = "Common.DVC_QuyenLienQuan_SearchCongDan.SubmitForm()", @onkeyup = "Common.DVC_QuyenLienQuan_SearchCongDan.SubmitForm()" })
        </div>
        <div class="form-group col-md-4">
            <label class="font-weight-bold">Ngày cấp</label>
            <div class="input-group">
                @Html.TextBoxFor(model => model.NgayCap, new { @class = "form-control form-control-sm w-50 datepicker-share", @placeholder = "Ngày cấp", @onchange = "Common.DVC_QuyenLienQuan_SearchCongDan.SubmitForm()" })
                <div class="input-group-prepend">
                    <label for="" class="input-group-text cursor"><i class="far fa-calendar-alt "></i></label>
                </div>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label class="font-weight-bold">ĐKKD</label>
            @Html.TextBoxFor(m => m.SoDKKD, new { @class = "form-control form-control-sm", @placeholder = "Nhập số ĐKKD", @onchange = "Common.DVC_QuyenLienQuan_SearchCongDan.SubmitForm()", @onkeyup = "Common.DVC_QuyenLienQuan_SearchCongDan.SubmitForm()" })
        </div>
        <div class="form-group col-md-4">
            <label class="font-weight-bold">Ngày cấp ĐKKD</label>
            <div class="input-group">
                @Html.TextBoxFor(model => model.NgayCapDKKD, new { @class = "form-control form-control-sm w-50 datepicker-share", @placeholder = "Ngày cấp ĐKKD", @onchange = "Common.DVC_QuyenLienQuan_SearchCongDan.SubmitForm()" })
                <div class="input-group-prepend">
                    <label for="" class="input-group-text cursor"><i class="far fa-calendar-alt "></i></label>
                </div>
            </div>
        </div>
        <div class="form-group col-md-4">
            <label class="font-weight-bold">Bút danh/Nghệ danh</label>
            @Html.TextBoxFor(m => m.ButDanh, new { @class = "form-control form-control-sm", @placeholder = "Nhập bút danh/nghệ danh", @onchange = "Common.DVC_QuyenLienQuan_SearchCongDan.SubmitForm()", @onkeyup = "Common.DVC_QuyenLienQuan_SearchCongDan.SubmitForm()" })
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-8">
            <label class="font-weight-bold">Địa chỉ</label>
            @Html.TextBoxFor(m => m.DiaChi, new { @class = "form-control form-control-sm", @placeholder = "Nhập địa chỉ", @onchange = "Common.DVC_QuyenLienQuan_SearchCongDan.SubmitForm()" })
        </div>
    </div>
    <div class="text-right mt-2">
        <button class="btn btn-info btn-sm text-white" type="button" id="btnSearchCongDan"><i class="fas fa-search mr-1"></i> Tìm kiếm</button>
        @if (admin == true || user.Right.Contains(CookieRight.TT_CongDan_InsUpd))
        {
            <button type="button" class="btn btn-success btn-block-sm btn-sm" id="btnInsertCongDan">
                <i class="fas fa-plus"></i> Thêm mới
            </button>
        }
    </div>
}