CMS.Admin/Controllers/DM_QuanHuyenController.cs
using Business.Entities.Domain;
using CMS.Admin.Common;
using CMS.Admin.Constaints;
using CMS.Admin.Models.DM_QuanHuyen;
using Module.Framework.Common;
using log4net;
using Module.Framework;
using PagedList;
using System;
using System.Linq;
using System.Web.Mvc;

namespace CMS.Admin.Controllers
{
    public class DM_QuanHuyenController : BaseController
    {
        #region dungchung
        private DungChungServiceClient _DungChungSrv;
        private int _pageSize;
        #endregion
        public DM_QuanHuyenController()
        {
            var pageSize = DungChung.GetKeyCauHinhHeThong("SoHangHienThi");
            if (!int.TryParse(pageSize, out this._pageSize))
                this._pageSize = 10;
        }
        // GET: DM_NhomQuyen
        [CustomAuthorize(RightName = CookieRight.DM_QuanHuyenController_Index)]

        public ActionResult Index()
        {
            if (DungChung.CheckTimeDN() == false)
            {
                return RedirectToAction("LogOff", "NguoiDungHeThong");
            }
            var result = new DM_QuanHuyenViewModel();
            result.Search = new DM_QuanHuyenMapParam();
            try
            {
                result.Search.PageSize = this._pageSize;
                result.Search.PageIndex = 1;
                _DungChungSrv = new DungChungServiceClient();
                var tempList = _DungChungSrv.DM_QuanHuyen_List(result.Search);
                if (tempList.Data != null && tempList.Data.resultObject != null && tempList.Data.resultObject.Any())
                {
                    DungChung.ghinhatkynguoidung("Xem danh sách quận huyện",
                                              "DM_QuanHuyenController",
                                              "Index", "View");
                    result.Items = tempList.Data.resultObject.ToPagedList(result.Search.PageIndex, result.Search.PageSize);
                }
                return View(result);
            }
            catch (Exception ex)
            {
                DungChung.ghiloghethong("DM_QuanHuyenController/Index error:" + ex.Message, ex, Request);
                return View(result);
            }
        }
        [HttpPost]
        public ActionResult TimKiem(DM_QuanHuyenMapParam model)
        {
            var result = new DM_QuanHuyenViewModel();
            try
            {
                _DungChungSrv = new DungChungServiceClient();
                //model.PageSize = this._pageSize;
                var tempList = _DungChungSrv.DM_QuanHuyen_List(model);
                if (tempList.Data != null && tempList.Data.resultObject != null && tempList.Data.resultObject.Any())
                {
                    DungChung.ghinhatkynguoidung("Tìm kiếm quận huyện",
                                              "DM_QuanHuyenController",
                                              "Index", "View");
                    result.Items = tempList.Data.resultObject.ToPagedList(1, model.PageSize);
                }
                return PartialView("_PartialList", result.Items);
            }
            catch (Exception ex)
            {
                DungChung.ghiloghethong("DM_QuanHuyenController/TimKiem error:" + ex.Message, ex, Request);
                return PartialView("_PartialList", result.Items);
            }
        }
        [HttpPost]
        [CustomAuthorize(RightName = CookieRight.Dm_QuanHuyenController_ThemMoi)]
        [CheckForAntiForgeryToken]

        public ActionResult ThemMoi(DM_QuanHuyenMapAdd model)
        {
            if (DungChung.CheckTimeDN() == false)
            {
                return RedirectToAction("LogOff", "NguoiDungHeThong");
            }
            bool status = false;
            try
            {
                if (model != null)
                {
                    _DungChungSrv = new DungChungServiceClient();
                    //kiem tra co tont tai ma chua
                    if (model.Id == 0)
                    {
                        var checkMa = _DungChungSrv.DM_QuanHuyen_GetByMa(model.Ma);
                        if (checkMa.Data != null && checkMa.Data.resultObject != null)
                            return Json(new { status = status, checkMa = true });
                    }
                    else
                    {
                        var temp = _DungChungSrv.DM_QuanHuyen_GetById(model.Id);
                        if (temp.Data != null && temp.Data.resultObject != null)
                        {
                            if (temp.Data.resultObject.Ma != model.Ma)
                            {
                                var checkMa = _DungChungSrv.DM_QuanHuyen_GetByMa(model.Ma);
                                if (checkMa.Data != null && checkMa.Data.resultObject != null)
                                {
                                    DungChung.ghinhatkynguoidung("Thêm mới quận huyện",
                                              "DM_QuanHuyenController",
                                              "ThemMoi", "Create");
                                    return Json(new { status = status, checkMa = true });
                                }
                            }
                        }
                    }
                    var result = _DungChungSrv.DM_QuanHuyen_InsUpd(model);
                    if (result.Data != null && result.Data.resultObject > 0)
                        status = true;
                }
                return Json(new { status = status, checkMa = false });
            }
            catch (Exception ex)
            {
                DungChung.ghiloghethong("DM_QuanHuyenController/ThemMoi error:" + ex.Message, ex, Request);
                return View(status);
            }

        }
        [HttpPost]
        public ActionResult CapNhat(long id)
        {
            var model = new DM_QuanHuyenMapAdd();
            try
            {
                if (id > 0)
                {
                    _DungChungSrv = new DungChungServiceClient();
                    var temp = _DungChungSrv.DM_QuanHuyen_GetById(id);
                    if (temp.Data != null && temp.Data.resultObject != null)
                        model = temp.Data.resultObject;
                }
                return PartialView("DialogUpdate/Update", model);
            }
            catch (Exception ex)
            {
                DungChung.ghiloghethong("DM_QuanHuyenController/Index error:" + ex.Message, ex, Request);
                return PartialView("DialogUpdate/Update", model);
            }

        }
        [CustomAuthorize(RightName = CookieRight.DM_QuanHuyenController_Xoa)]

        public ActionResult Xoa(long id)
        {
            if (DungChung.CheckTimeDN() == false)
            {
                return RedirectToAction("LogOff", "NguoiDungHeThong");
            }
            bool status = false;
            try
            {
                if (id > 0)
                {
                    _DungChungSrv = new DungChungServiceClient();
                    Guid userId = Guid.NewGuid();
                    var temp = _DungChungSrv.DM_QuanHuyen_Delete(id, userId);
                    if (temp.Data != null && temp.Data.resultObject == true)
                    {
                        DungChung.ghinhatkynguoidung("Xóa quận huyện",
                                              "DM_QuanHuyenController",
                                              "Xoa", "Delete");
                        status = temp.Data.resultObject;
                    }
                }
                return Json(new { status = status });
            }
            catch (Exception ex)
            {
                DungChung.ghiloghethong("DM_QuanHuyenController/Xoa error:" + ex.Message, ex, Request);
                return Json(new { status = status });
            }

        }
    }
}

CMS.Admin/Controllers/PrintController.cs
using Aspose.Cells;
using Aspose.Words;
using Business.Entities.Domain;
using Core.Common.Utilities;
using Module.Framework;
using Newtonsoft.Json;
using System;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace CMS.Admin.Controllers
{
    public class PrintController : BaseController
    {
        private DungChungServiceClient _DungChungSrv;
        // GET: Print
        #region Export File Excel
        public ActionResult ExportFileExcel(string Param, string Key)
        {
            try
            {
                using (_DungChungSrv = new DungChungServiceClient())
                {
                    string result = string.Empty;
                    var _dt = _DungChungSrv.GetInfoParametersByKeyCode(Key);
                    if (_dt != null && _dt.Data != null && _dt.Data.resultObject != null)
                    {
                        var _dtParam = _dt.Data.resultObject;
                        Print_DataMap model = new Print_DataMap();
                        model.StoreProcedure = _dtParam.Procdures;
                        model.Parameters = Param.ToString();
                        var _result = _DungChungSrv.Print(model);
                        var _data = (_result != null && _result.Data != null && _result.Data.StatusCode == 200 && _result.Data.resultObject != null) ? _result.Data.resultObject : null;
                        if (!string.IsNullOrEmpty(_data))
                        {
                            var pathExport = Server.MapPath(_dtParam.Path);
                            var wbExport = new Workbook();
                            wbExport.Open(pathExport);
                            DataSet Data = JsonConvert.DeserializeObject<DataSet>(_data);
                            var ds = new DataSet("office");
                            ds = Data;

                            int iIndex = _dtParam.RowStart - 1; //start
                            int _countColumns = _dtParam.TotalCoumns; // tổng số columns

                            if (Key == "ExportQTG_QuyenTacGiaList_Excel" || Key == "ExportQLQ_QuyenLienQuanList_Excel")
                            {
                                string[] stringArray = { ".gif", ".jpg", ".jpeg", ".png" };
                                if (ds.Tables.Count > 0)
                                {
                                    int i = 0, j = 0;
                                    DataTable dt = ds.Tables[0];

                                    for (i = 0; i < dt.Rows.Count; i++)
                                    {
                                        var _ColumnsData = dt.Rows[i];
                                        for (j = 0; j < _countColumns; j++)
                                        {
                                            if (_ColumnsData[j].ToString() != "" && Array.Exists(stringArray, e => _ColumnsData[j].ToString().Contains(e)))
                                            {
                                                var path = Path.Combine(Server.MapPath('~' + _ColumnsData[j].ToString()));
                                                if (System.IO.File.Exists(path))
                                                {
                                                    wbExport.Worksheets[0].Cells.SetRowHeight(iIndex, 64);
                                                    wbExport.Worksheets[0].Cells.SetColumnWidth(j, 12);
                                                    wbExport.Worksheets[0].Pictures.Add(iIndex, j, iIndex + 1, j + 1, path);
                                                }
                                            }
                                            else
                                            {
                                                var str = HttpUtility.HtmlDecode(_ColumnsData[j].ToString());
                                                wbExport.Worksheets[0].Cells[iIndex, j].Value = Regex.Replace(str, "<.*?>", String.Empty).Trim();
                                            }
                                        }
                                        iIndex++;
                                    }

                                    if (ds.Tables.Count == 2)
                                    {
                                        var dt2 = ds.Tables[1];
                                        var cells = wbExport.Worksheets[0].Cells;
                                        var opts = new FindOptions();
                                        Cell startcell = null;
                                        for (i = 0; i < dt2.Columns.Count; i++)
                                        {
                                            startcell = null;
                                            do
                                            {
                                                startcell = cells.Find("<<" + dt2.Columns[i] + ">>", startcell, opts);
                                                if (startcell != null)
                                                {

                                                    if (dt2.Rows.Count > 0)
                                                        startcell.Value = dt2.Rows[0][i];
                                                    else
                                                        startcell.Value = "";
                                                }
                                            } while (startcell != null);
                                        }
                                        startcell = null;
                                        do
                                        {
                                            startcell = cells.Find("<<", startcell, opts);
                                            if (startcell != null)
                                            {
                                                startcell.Value = "";
                                            }
                                        } while (startcell != null);
                                    }

                                }
                                CommonHelper.FullStyleBorderExcel(wbExport, _dtParam.StartColumns + (_dtParam.RowStart - 1), _dtParam.EndColumns + (iIndex));
                                var namefile = _dtParam.Description + "_" + string.Format("{0:yyyyMMddhhmmssfff}", DateTime.Now) + ".xlsx";
                                using (MemoryStream ms = new MemoryStream())
                                {
                                    wbExport.Save(ms, Aspose.Cells.SaveFormat.Xlsx);
                                    ms.Position = 0;
                                    byte[] byteBuffer = ms.ToArray();
                                    ms.Close();
                                    result = Convert.ToBase64String(byteBuffer);
                                    byteBuffer = null;
                                }
                                return Json(new { data = result, fileName = namefile }, JsonRequestBehavior.AllowGet);
                            }
                            else
                            {
                                if (ds.Tables.Count > 0)
                                {
                                    int i = 0, j = 0;
                                    DataTable dt = ds.Tables[0];

                                    for (i = 0; i < dt.Rows.Count; i++)
                                    {
                                        var _ColumnsData = dt.Rows[i];
                                        for (j = 0; j < _countColumns; j++)
                                        {
                                            var str = HttpUtility.HtmlDecode(_ColumnsData[j].ToString());
                                            wbExport.Worksheets[0].Cells[iIndex, j].Value = Regex.Replace(str, "<.*?>", String.Empty).Trim();
                                        }
                                        iIndex++;
                                    }

                                    if (ds.Tables.Count == 2)
                                    {
                                        var dt2 = ds.Tables[1];
                                        var cells = wbExport.Worksheets[0].Cells;
                                        var opts = new FindOptions();
                                        Cell startcell = null;
                                        for (i = 0; i < dt2.Columns.Count; i++)
                                        {
                                            startcell = null;
                                            do
                                            {
                                                startcell = cells.Find("<<" + dt2.Columns[i] + ">>", startcell, opts);
                                                if (startcell != null)
                                                {

                                                    if (dt2.Rows.Count > 0)
                                                        startcell.Value = dt2.Rows[0][i];
                                                    else
                                                        startcell.Value = "";
                                                }
                                            } while (startcell != null);
                                        }
                                        startcell = null;
                                        do
                                        {
                                            startcell = cells.Find("<<", startcell, opts);
                                            if (startcell != null)
                                            {
                                                startcell.Value = "";
                                            }

CMS.Admin/Views/DM_QuanHuyen/Index.cshtml
@using Module.Framework.Common;
@using CMS.Admin.Constaints;
@{
    ViewBag.Title = "Danh mục quận huyện";
    var user = LoginManager.GetCurrentUser();
    var admin = LoginManager.CheckAdmin();
}

@model CMS.Admin.Models.DM_QuanHuyen.DM_QuanHuyenViewModel
<div class="card bg-white w-100">
    <div class="card-header">
        <h4 class="card-title">Danh sách quận huyện</h4>
        <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
        <div class="heading-elements">
            <ul class="list-inline mb-0">
                <li class="cursor"><a data-action="collapse"><i class="fas fa-minus"></i></a></li>
                <li class="cursor"><a data-action="reload"><i class="fas fa-sync-alt"></i></a></li>
                <li class="cursor"><a data-action="expand"><i class="fas fa-expand"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="card-content collapse show">
        <div class="card-body">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    @if (admin == true || user.Right.Contains(CookieRight.Dm_QuanHuyenController_ThemMoi))
                    {
                        <button type="button" class="btn btn-success btn-block-sm btn-sm mt-md-0 mt-sm-2 text-white" id="btnAddForm">
                            <i class="fas fa-plus mr-1"></i> Thêm mới
                        </button>
                    }
                    @*<button type="button" class="btn btn-primary btnExportQuanHuyen btn-block-sm btn-sm mt-md-0 mt-sm-2">
                            <i class="fas fa-download mr-1"></i> Xuất excel
                        </button>*@
                </div>
                <div class="col-md-6 col-sm-12 text-right mt-md-0 mt-sm-3">
                    @Html.Partial("_PartialSearch", Model.Search)
                </div>
            </div>
            <div class="table-responsive mt-3" id="result-searchlist">
                @if (Model != null && Model.Items != null && Model.Items.Any())
                {
                    @Html.Partial("_PartialList", Model.Items)
                }
                else
                {
                    <div class="alert alert-info mt-3" role="alert">
                        Không có dữ liệu
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@{Html.RenderPartial("DialogUpdate/Index");}
<!-- end Dialog update--->
@{
    <script type="text/javascript" src="@Url.Content("~/Scripts/DM_QuanHuyen.js")"></script>
}
<script>
    $(document).ready(function () {
        if (Common.Empty(Common.DMQuanHuyen)) {
            Common.DMQuanHuyen = new DMQuanHuyen({
                  Url: {
                    Delete: '@Url.Action("Xoa", "DM_QuanHuyen")',
                    Create: '@Url.Action("ThemMoi", "DM_QuanHuyen")',
                    Update: '@Url.Action("CapNhat", "DM_QuanHuyen")',
                    ExportExcel:'@Url.Action("ExportFileExcel", "Print")',
                },
            });
        }
        else {
            Common.DMQuanHuyen.RegisterEvent();
        }
    });
</script>

CMS.Admin/Views/DM_QuanHuyen/_PartialList.cshtml
@using PagedList;
@using Core.Common.Common;
@using Module.Framework.Common;
@using CMS.Admin.Constaints;
@model IPagedList<Business.Entities.Domain.DM_QuanHuyenMap>
@{
    var user = LoginManager.GetCurrentUser();
    var admin = LoginManager.CheckAdmin();
}
<table id="recent-orders" class="table table-hover mb-0 table-striped table-mobile table-bordered">
    <thead>
        <tr class="bg-info text-white">
            @*<th class="text-center cursor" width="50">STT</th>*@
            <th class="text-center cursor" width="150">Mã quận huyện</th>
            <th class="text-center cursor" width="150">Mã quận huyện liên thông</th>
            <th width="300">Tên quận huyện</th>
            <th width="300">Tên tỉnh thành</th>
            <th>Mô tả</th>
            <th class="text-center" width="150">Thứ tự hiển thị</th>
            <th class="text-center" width="120">Công khai</th>
            @if (admin == true || user.Right.Contains(CookieRight.Dm_QuanHuyenController_ThemMoi) || user.Right.Contains(CookieRight.DM_QuanHuyenController_Xoa))
            {
                <th class="text-center" width="100">Thao tác</th>
            }
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            int i = 1;
            foreach (var item in Model)
            {
        <tr data-id="@item.Id">
            @*<td class="text-center hidden-xs">@i</td>*@
            <td class="text-center" data-label="Mã quận huyện">@Html.Raw(item.Ma ?? "&nbsp;")</td>
            <td class="text-center" data-label="Mã quận huyện liên thông">@Html.Raw(item.MaLienThong ?? "&nbsp;")</td>
            <td data-label="Tên quận huyện">@Html.Raw(item.Ten ?? "&nbsp;")</td>
            <td data-label="Tên tỉnh thành">@Html.Raw(item.TenTinhThanh ?? "&nbsp;")</td>
            <td data-label="Mô tả">@Html.Raw(item.MoTa ?? "&nbsp;")</td>
            <td data-label="Thứ tự hiển thị" class="text-center">@item.ThuTuHienThi</td>
            <td class="text-center text-success" data-label="Công khai">@Html.Raw(item.CongKhai ? "<i class='fas fa-check'></i>" : "&nbsp;")</td>
            @if (admin == true || user.Right.Contains(CookieRight.Dm_QuanHuyenController_ThemMoi) || user.Right.Contains(CookieRight.DM_QuanHuyenController_Xoa))
            {
                <td class="text-center" data-label="Thao tác">
                    @if (admin == true || user.Right.Contains(CookieRight.Dm_QuanHuyenController_ThemMoi))
                    {
                        <button title="Chỉnh sửa" class="btn btn-primary btn-sm btnUpdate" type="button"><i class="far fa-edit"></i></button>
                    }
                    @if (admin == true || user.Right.Contains(CookieRight.DM_QuanHuyenController_Xoa))
                    {
                        <button title="Xóa" class="btn btn-danger btn-sm btnDelete" type="button"><i class="far fa-trash-alt"></i></button>
                    }
                </td>
            }
        </tr>
                i++;
            }
        }
        else
        {
            <tr>
                <td colspan="6">
                    <div class="alert alert-info mt-3" role="alert">
                        Không có dữ liệu
                    </div>
                </td>
            </tr>
        }
</table>
@if (Model != null && Model.Any())
{
    <!--- Pagination -->
    <div class="paging-bottom">
        @Html.Raw(Ajax.Pager(
                new Options
                {
                    PageSize = Model.PageSize,
                    TotalItemCount = Model[0].TotalCount,
                    CurrentPage = Model[0].PageIndex,
                    IsShowControls = true,
                    IsShowFirstLast = true,
                    LimitPage = 5,
                    Link = "javascript:void(0);",
                    OnClick = "Common.DMQuanHuyen.Paging({0})",
                    OnChangePageSize = "Common.DMQuanHuyen.ChangePageSize(this)",
                }))
    </div>
    <!--- End Pagination -->
}

CMS.Admin/Views/DM_QuanHuyen/_PartialSearch.cshtml
@using CMS.Admin.Common
@model Business.Entities.Domain.DM_QuanHuyenMapParam
@using (Ajax.BeginForm("TimKiem", "DM_QuanHuyen", null, new AjaxOptions
{
    UpdateTargetId = "result-searchlist",
    HttpMethod = "Post",
    OnBegin = "Common.DMQuanHuyen.BeforeSend",
    OnSuccess = "Common.DMQuanHuyen.Success",
    OnFailure = "Common.ErrorMessage"
}, new { @class = "", @role = "form", @id = "IdformSearch" }))
{
<div class="hidden">
    @Html.HiddenFor(m => m.PageIndex)
    @Html.HiddenFor(m => m.PageSize)
</div>
    <div class="input-group">
        @Html.TextBoxFor(m => m.TuKhoa, new { @class = "form-control form-control-sm w-50", @placeholder = "Nhập thông tin cần tìm" })
        @Html.DropDownListFor(m => m.TinhThanhID, CBODungChung.GetCBOTinhThanh(), "--Chọn tỉnh thành--", new { @class = "form-control form-control-sm select-share w-25" })
        <div class="input-group-prepend">
            <button class="btn btn-info btn-sm text-white" type="submit" id="btnFormSearch"><i class="fas fa-search mr-1"></i> Tìm kiếm</button>
        </div>
    </div>
}