CMS.Admin/Models/QTG_QuyenTacGia/QTG_CapDoiViewModel.cs
using Business.Entities.Domain;

namespace CMS.Admin.Models
{
    public class QTG_CapDoiViewModel
    {
        public QTG_QuyenTacGiaAdd QuyenTacGia { get; set; }
        public QTG_CapDoiAdd CapDoi { get; set; }
    }
}

CMS.Admin/Models/QTG_QuyenTacGia/QTG_CapLaiViewModel.cs
using Business.Entities.Domain;

namespace CMS.Admin.Models
{
    public class QTG_CapLaiViewModel
    {
        public QTG_QuyenTacGiaAdd QuyenTacGia { get; set; }
        public QTG_CapLaiAdd CapLai { get; set; }
    }
}

CMS.Admin/Models/QTG_QuyenTacGia/QTG_ChuyenChuViewModel.cs
using Business.Entities.Domain;

namespace CMS.Admin.Models
{
    public class QTG_ChuyenChuViewModel
    {
        public QTG_QuyenTacGiaAdd QuyenTacGia { get; set; }
        public QTG_ChuyenChuSoHuuAdd ChuyenChu { get; set; }
    }
}

CMS.Admin/Models/QTG_QuyenTacGia/QTG_FileViewModel.cs
namespace CMS.Admin.Models
{
    public class QTG_FileViewModel
    {
        public string Url { get; set; }
        public bool IsMotCua { get; set; }
    }
}

CMS.Admin/Models/QTG_QuyenTacGia/QTG_QuyenTacGiaViewModel.cs
using Business.Entities.Domain;
using PagedList;

namespace CMS.Admin.Models
{
    public class QTG_QuyenTacGiaViewModel
    {
        public QTG_QuyenTacGiaParam Search { get; set; }
        public IPagedList<QTG_QuyenTacGiaMap> List { get; set; }
    }
}

CMS.Admin/Models/QTG_QuyenTacGia/QTG_ThuHoiViewModel.cs
using Business.Entities.Domain;

namespace CMS.Admin.Models
{
    public class QTG_ThuHoiViewModel
    {
        public QTG_QuyenTacGiaAdd QuyenTacGia { get; set; }
        public QTG_ThuHoiAdd ThuHoi { get; set; }
    }
}

CMS.Admin/Controllers/QTG_QuyenTacGiaController.cs
using Business.Entities.Domain;
using CMS.Admin.Common;
using CMS.Admin.Constaints;
using CMS.Admin.Models;
using Module.Framework.Common;
using Module.Framework;
using PagedList;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Collections.Generic;
using Newtonsoft.Json;
using System.IO;
using Core.Common.Utilities;
using Module.Framework.Utilities;
using System.Web.Configuration;
using System.Net;

namespace CMS.Admin.Controllers
{
    public class QTG_QuyenTacGiaController : BaseController
    {
        private int _pageSize;
        private Guid _nguoiDungID;
        private long _userPortalID;
        public QTG_QuyenTacGiaController()
        {
            var pageSize = DungChung.GetKeyCauHinhHeThong("SoHangHienThi");
            if (!int.TryParse(pageSize, out this._pageSize))
                this._pageSize = 10;
            _nguoiDungID = LoginManager.GetCurrentUser() != null ? Guid.Parse(LoginManager.GetCurrentUser().UserId) : Guid.Empty;
            _userPortalID = LoginManager.GetCurrentUser() != null ? LoginManager.GetCurrentUser().UserPortalID : 0;
        }

        #region QuyenTacGia
        [CustomAuthorize(RightName = CookieRight.QTG_QuyenTacGia_Index)]
        public ActionResult Index()
        {
            if (DungChung.CheckTimeDN() == false)
            {
                return RedirectToAction("LogOff", "NguoiDungHeThong");
            }
            var result = new QTG_QuyenTacGiaViewModel();
            result.Search = new QTG_QuyenTacGiaParam();
            try
            {
                result.Search.PageSize = this._pageSize;
                result.Search.PageIndex = 1;
                using (var _quyenTacGiaSVR = new QuyenTacGiaServiceClient())
                {
                    var tempList = _quyenTacGiaSVR.QTG_QuyenTacGia_List(result.Search);
                    if (tempList.Data != null && tempList.Data.resultObject != null && tempList.Data.resultObject.Any())
                    {
                        DungChung.ghinhatkynguoidung("Xem danh sách quyền tác giả",
                                               "QTG_QuyenTacGiaController",
                                               "Index", "View");
                        result.List = tempList.Data.resultObject.ToPagedList(1, result.Search.PageSize);
                    }
                }
                return View(result);
            }
            catch (Exception ex)
            {
                DungChung.ghiloghethong("QTG_QuyenTacGiaController/Index error:" + ex.Message, ex, Request);
                return View(result);
            }
        }
        [HttpPost]
        public ActionResult Index(QTG_QuyenTacGiaParam model)
        {
            if (DungChung.CheckTimeDN() == false)
            {
                return RedirectToAction("LogOff", "NguoiDungHeThong");
            }
            var result = new QTG_QuyenTacGiaViewModel();
            try
            {
                //model.PageSize = this._pageSize;
                using (var _quyenTacGiaSVR = new QuyenTacGiaServiceClient())
                {
                    var tempList = _quyenTacGiaSVR.QTG_QuyenTacGia_List(model);
                    if (tempList.Data != null && tempList.Data.resultObject != null && tempList.Data.resultObject.Any())
                    {
                        DungChung.ghinhatkynguoidung("Xem danh sách quyền tác giả",
                                               "QTG_QuyenTacGiaController",
                                               "Index", "View");
                        result.List = tempList.Data.resultObject.ToPagedList(1, model.PageSize);
                    }
                }
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_IndexPartialView", result);
                }
                return View(result);
            }
            catch (Exception ex)
            {
                DungChung.ghiloghethong("QTG_QuyenTacGiaController/Index error:" + ex.Message, ex, Request);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_IndexPartialView", result);
                }
                return View(result);
            }
        }

        [CustomAuthorize]
        [CustomAuthorize(RightName = CookieRight.QTG_QuyenTacGia_InsUpd)]
        public ActionResult Insert(string id)
        {
            if (DungChung.CheckTimeDN() == false)
            {
                return RedirectToAction("LogOff", "NguoiDungHeThong");
            }
            var result = new QTG_QuyenTacGiaAdd();
            result.LoaiDangKyID = 1;
            result.HinhDaiDienStt = -1;
            result.PhimStt = -1;
            result.NgayCap = DateTime.Today.ToString("dd/MM/yyyy");
            try
            {
                ViewBag.TieuDe = "Cấp giấy chứng nhận đăng ký quyền tác giả - Nhập tác phẩm";
                if (id != "" && id != null)
                {
                    using (var _quyenTacGiaSVR = new QuyenTacGiaServiceClient())
                    {
                        var tempList = _quyenTacGiaSVR.QTG_QuyenTacGia_ById(long.Parse(id));
                        if (tempList != null && tempList.Data != null && tempList.Data.resultObject != null)
                        {
                            result = tempList.Data.resultObject;
                        }
                    }
                }
                return View(result);
            }
            catch (Exception ex)
            {
                DungChung.ghiloghethong("QTG_QuyenTacGiaController/Insert error:" + ex.Message, ex, Request);
                return View(result);
            }
        }

        [CustomAuthorize]
        [CustomAuthorize(RightName = CookieRight.QTG_QuyenTacGia_InsUpd)]
        public ActionResult CapMoi(string id, string hoSoId, bool? isMap)
        {
            if (DungChung.CheckTimeDN() == false)
            {
                return RedirectToAction("LogOff", "NguoiDungHeThong");
            }
            int hoSoOnlineID = 0;
            var result = new QTG_QuyenTacGiaAdd();
            result.ListDinhKem = new List<QTG_DinhKemAdd>();
            result.LoaiDangKyID = 1;
            result.HinhDaiDienStt = -1;
            result.PhimStt = -1;
            result.NgayCap = DateTime.Today.ToString("dd/MM/yyyy");
            if (hoSoId != "" && hoSoId != null)
                result.HoSoID = long.Parse(hoSoId);
            try
            {
                ViewBag.TieuDe = "Cấp giấy chứng nhận đăng ký quyền tác giả - Nhập tác phẩm";
                //isMap == true đi từ màn hình hồ sơ qua
                //isMap == null chọn từ kho DVC
                if (hoSoId != "" && hoSoId != null)
                {
                    if (!string.IsNullOrEmpty(id) && isMap == null)
                    {
                        using (var _dvcQuyenTacGiaSVR = new DVC_QuyenTacGiaServiceClient())
                        {
                            var tempList = _dvcQuyenTacGiaSVR.DVC_QTG_QuyenTacGia_ById(long.Parse(id));
                            if (tempList != null && tempList.Data != null && tempList.Data.resultObject != null)
                            {
                                result.STT = tempList.Data.resultObject.STT;
                                result.VungMienID = tempList.Data.resultObject.VungMienID;
                                result.CoNguoiDaiDien = tempList.Data.resultObject.CoNguoiDaiDien;
                                result.NDDHoVaTen = tempList.Data.resultObject.NDDHoVaTen;
                                result.NDDSoCMND = tempList.Data.resultObject.NDDSoCMND;
                                result.NDDSoDienThoai = tempList.Data.resultObject.NDDSoDienThoai;
                                result.NDDDiaChi = tempList.Data.resultObject.NDDDiaChi;
                                result.IsToChuc = tempList.Data.resultObject.IsToChuc;
                                result.LoaiDangKyID = tempList.Data.resultObject.LoaiDangKyID;
                                result.NgayHT = tempList.Data.resultObject.NgayHT;
                                result.TenTacPham = tempList.Data.resultObject.TenTacPham;
                                result.PhimID = tempList.Data.resultObject.PhimID;
                                result.PhimStt = tempList.Data.resultObject.PhimStt;
                                result.TenPhim = tempList.Data.resultObject.TenPhim;
                                result.TrangThaiCongBoID = tempList.Data.resultObject.TrangThaiCongBoID;
                                result.NgayCongBo = tempList.Data.resultObject.NgayCongBo;
                                result.LoaiHinhID = tempList.Data.resultObject.LoaiHinhID;
                                result.NoiCongBo = tempList.Data.resultObject.NoiCongBo;
                                result.HinhDaiDienID = tempList.Data.resultObject.HinhDaiDienID;
                                result.HinhDaiDienStt = tempList.Data.resultObject.HinhDaiDienStt;
                                result.HinhDaiDienUrl = tempList.Data.resultObject.HinhDaiDienUrl;
                                result.LoaiNghiepVuID = tempList.Data.resultObject.LoaiNghiepVuID;
                                result.TenLoaiNghiepVu = tempList.Data.resultObject.TenLoaiNghiepVu;
                                result.IsDauKy = tempList.Data.resultObject.IsDauKy;
                                result.TrangThaiID = tempList.Data.resultObject.TrangThaiID;
                                result.TenTrangThai = tempList.Data.resultObject.TenTrangThai;
                                result.KeyMapID = tempList.Data.resultObject.KeyMapID;
                                result.SoLanCapLai = tempList.Data.resultObject.SoLanCapLai;
                                result.SoLanThuHoi = tempList.Data.resultObject.SoLanThuHoi;
                                result.SoLanCapDoi = tempList.Data.resultObject.SoLanCapDoi;

CMS.Admin/Views/QTG_QuyenTacGia/DialogSearchTacGia/Index.cshtml
@using Module.Framework.Common;
@{
    var user = LoginManager.GetCurrentUser();
    var admin = LoginManager.CheckAdmin();
    var modelParam = new Business.Entities.Domain.TT_TacGiaParam();
    var modelList = new List<Business.Entities.Domain.TT_TacGiaMap>();
    var modelAdd = new Business.Entities.Domain.TT_TacGiaAdd();
}
<script src="~/Scripts/QTG_QuyenTacGia/QTG_QuyenTacGia_SearchTacGia.js"></script>
<div class="modal fade custom-margin-form-group" id="dialogSearchTacGia" aria-hidden="false" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header h-25">
                <h5 class="modal-title">Thông tin tác giả </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group sh-search-tacgia">
                    @Html.Partial("DialogSearchTacGia/Search", modelParam)
                </div>
                <div class="form-group sh-info-tacgia hidden">
                    <form role="form" id="form-update-tacgia" class="form-horizontal label-right">
                        @Html.Partial("DialogSearchTacGia/Update", modelAdd)
                    </form>
                </div>
                <div class="table-responsive mt-3" id="result-searchtacgia">
                    @Html.Partial("DialogSearchTacGia/List", modelList)
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success btn-sm" id="btnAddTacGia"><i class="far fa-save mr-1"></i> Chọn</button>
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal"><i class="fas fa-times mr-2"></i> Đóng</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        if (Common.Empty(Common.QTG_QuyenTacGia_SearchTacGia)) {
            Common.QTG_QuyenTacGia_SearchTacGia = new QTG_QuyenTacGia_SearchTacGia({
                Url: {
                    SearchTacGia: '@Url.Action("SearchTacGia", "QTG_QuyenTacGia")',
                    SaveTacGia: '@Url.Action("SaveTacGia", "QTG_QuyenTacGia")',
                    UpdateTacGia: '@Url.Action("UpdateTacGia", "QTG_QuyenTacGia")',
                },
                ListTacGia: [],
            });
            $("#tableTacGia tbody tr").each(function () {
                if ($(this).closest("tr").data("id") > 0) {
                    Common.QTG_QuyenTacGia_SearchTacGia.ListTacGia.push({
                        TacGiaID: $(this).closest("tr").data("id"),
                        HoVaTen: $(this).closest("tr").data("name"),
                        QuocTich: $(this).closest("tr").data("country"),
                        SoCMND: $(this).closest("tr").data("cccd"),
                        DiaChi: $(this).closest("tr").data("address")
                    });
                }
            });
        }
        else {
            Common.QTG_QuyenTacGia_SearchTacGia.RegisterEvent();
        }
    });
</script>

CMS.Admin/Views/QTG_QuyenTacGia/DialogSearchTacGia/List.cshtml
@using Core.Common.Common;
@using Module.Framework.Common;
@using CMS.Admin.Constaints;
@{
    var user = LoginManager.GetCurrentUser();
    var admin = LoginManager.CheckAdmin();

}
@model List<Business.Entities.Domain.TT_TacGiaMap>

<table id="table-tacgia" cellspacing="0" cellpadding="0" class="table table-hover mb-0 table-striped table-mobile table-bordered">
    <thead>
        <tr class="thead-row bg-info text-white">
            <th class="text-center cursor" width="30"> <input type="checkbox" class="cursor" id="selectAllCheckBoxTG"></th>
            <th width="200">Họ và Tên</th>
            <th width="100">Bút danh/Nghệ danh</th>
            <th width="100">Quốc tịch</th>
            <th width="100">CCCD/Hộ chiếu</th>
            <th width="100">Ngày cấp</th>
            <th width="300">Địa chỉ</th>
            <th width="50" class="text-center">Thao tác</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                <tr data-id="@item.TacGiaID" data-name="@item.HoVaTen" data-country="@item.QuocTich" data-cccd="@item.SoCMND" data-address="@item.DiaChi" class="trTacGia cursor">
                    <td class="text-center"><input type="checkbox" class="cursor" name="chkInputCheckedTG[]"></td>
                    <td data-label="Họ và Tên">@Html.Raw(item.HoVaTen ?? "&nbsp;")</td>
                    <td data-label="Bút danh/Nghệ danh">@Html.Raw(item.ButDanh ?? "&nbsp;")</td>
                    <td data-label="Quốc tịch">@Html.Raw(item.QuocTich ?? "&nbsp;")</td>
                    <td data-label="CCCD/Hộ chiếu">@Html.Raw(item.SoCMND ?? "&nbsp;")</td>
                    <td data-label="Ngày cấp">@Html.Raw(item.NgayCap ?? "&nbsp;")</td>
                    <td data-label="Địa chỉ">@Html.Raw(item.DiaChi ?? "&nbsp;")</td>
                    <td data-label="Thao tác" class="text-center">
                        @if (admin == true || user.Right.Contains(CookieRight.TT_TacGia_InsUpd))
                        {
                            <button title="Chỉnh sửa" data-id="@item.TacGiaID" class="btn btn-primary btn-sm btn-update-tacgia" type="button"><i class="far fa-edit"></i></button>
                        }
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="7">
                    <div class="alert alert-info mt-3" role="alert">
                        Không có dữ liệu
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (Model != null && Model.Any())
{
    <!--- Pagination -->
    <div class="paging-bottom">
        @Html.Raw(Ajax.Pager(
                new Options
                {
                    PageSize = Model[0].PageSize,
                    TotalItemCount = Model[0].TotalCount,
                    CurrentPage = Model[0].PageIndex,
                    IsShowControls = true,
                    IsShowFirstLast = true,
                    LimitPage = 5,
                    Link = "javascript:void(0);",
                    OnClick = "Common.QTG_QuyenTacGia_SearchTacGia.Paging({0})",
                    OnChangePageSize = "Common.QTG_QuyenTacGia_SearchTacGia.ChangePageSize(this)",
                }))
    </div>
    <!--- End Pagination -->
}

CMS.Admin/Views/QTG_QuyenTacGia/DialogSearchTacGia/Search.cshtml
@using Module.Framework.Common;
@using CMS.Admin.Constaints;
@model Business.Entities.Domain.TT_TacGiaParam
@{
    var user = LoginManager.GetCurrentUser();
    var admin = LoginManager.CheckAdmin();
}
@using (Ajax.BeginForm("SearchTacGia", "QTG_QuyenTacGia", null, new AjaxOptions
{
    HttpMethod = "Post",
    OnBegin = "Common.QTG_QuyenTacGia_SearchTacGia.BeforeSend",
    OnSuccess = "Common.QTG_QuyenTacGia_SearchTacGia.Success",
    OnFailure = "Common.ErrorMessage"
}, new { @class = "", @role = "form", @id = "idFormSearchTacGia" }))
{
    <div class="hidden">
        @Html.HiddenFor(m => m.PageIndex)
        @Html.HiddenFor(m => m.PageSize)
    </div>

    <div class="form-row">
        <div class="form-group col-md-4">
            <label class="font-weight-bold">Họ và tên</label>
            @Html.TextBoxFor(m => m.HoVaTen, new { @class = "form-control form-control-sm", @placeholder = "Nhập tên tác giả", @onchange = "Common.QTG_QuyenTacGia_SearchTacGia.SubmitForm()", @onkeyup = "Common.QTG_QuyenTacGia_SearchTacGia.SubmitForm()" })
        </div>
        <div class="form-group col-md-4">
            <label class="font-weight-bold">Số CMNN/Hộ chiếu</label>
            @Html.TextBoxFor(m => m.SoCMND, new { @class = "form-control form-control-sm", @placeholder = "Nhập số CMNN/hộ chiếu", @onchange = "Common.QTG_QuyenTacGia_SearchTacGia.SubmitForm()", @onkeyup = "Common.QTG_QuyenTacGia_SearchTacGia.SubmitForm()" })
        </div>
        <div class="form-group col-md-4">
            <label class="font-weight-bold">Ngày cấp</label>
            <div class="input-group">
                @Html.TextBoxFor(model => model.NgayCap, new { @class = "form-control form-control-sm w-50 datepicker-share", @placeholder = "Ngày cấp" })
                <div class="input-group-prepend">
                    <label for="" class="input-group-text cursor"><i class="far fa-calendar-alt "></i></label>
                </div>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label class="font-weight-bold">Địa chỉ</label>
            @Html.TextBoxFor(m => m.DiaChi, new { @class = "form-control form-control-sm", @placeholder = "Nhập địa chỉ" })
        </div>
        <div class="form-group col-md-4">
            <label class="font-weight-bold">Bút danh/Nghệ danh</label>
            @Html.TextBoxFor(m => m.ButDanh, new { @class = "form-control form-control-sm", @placeholder = "Nhập bút danh/nghệ danh", @onchange = "Common.QTG_QuyenTacGia_SearchTacGia.SubmitForm()", @onkeyup = "Common.QTG_QuyenTacGia_SearchTacGia.SubmitForm()" })
        </div>
    </div>

    <div class="text-right mt-2">
        <button class="btn btn-info btn-sm text-white" type="button" id="btnSearchTacGia"><i class="fas fa-search mr-1"></i> Tìm kiếm</button>
        @if (admin == true || user.Right.Contains(CookieRight.TT_TacGia_InsUpd))
        {
            <button type="button" class="btn btn-success btn-block-sm btn-sm" id="btnInsertTacGia">
                <i class="fas fa-plus"></i> Thêm mới
            </button>
        }
    </div>
}

CMS.Admin/Views/QTG_QuyenTacGia/DialogSearchTacGia/Update.cshtml
@using Module.Framework.Common;
@using CMS.Admin.Constaints;
@using CMS.Admin.Common;
@model Business.Entities.Domain.TT_TacGiaAdd
@{
    var user = LoginManager.GetCurrentUser();
    var admin = LoginManager.CheckAdmin();
}
<div class="hidden">
    @Html.HiddenFor(m => m.TacGiaID)
</div>
<div class="form-row">
    <div class="form-group col-md-4">
        <label class="font-weight-bold">Họ và tên <span class="text-danger font-weight-bold">(*)</span></label>
        @Html.TextBoxFor(model => model.HoVaTen, new
        {
            @class = "form-control form-control-sm",
            @placeholder = "Nhập họ và tên tác giả",
            @data_rule_required = "true",
            @data_msg_required = "Vui lòng nhập họ và tên tác giả!!!",
            @data_rule_javascript = true,
            @data_msg_javascript = "Họ và tên tác giả không có đoạn Javascript không hợp lệ !!!",
            @data_rule_maHtml = true,
            @data_msg_maHtml = "Họ và tên tác giả không được chứa mã HTML!!!",
            @data_rule_maxlength = true,
            @data_value_maxlength = 100,
            @data_msg_maxlength = "Họ và tên tác giả không quá 100 ký tự!!!",
        })
    </div>
    <div class="form-group col-md-4">
        <label class="font-weight-bold">Quốc tịch <span class="text-danger">(*)</span></label>
        @Html.DropDownListFor(model => model.QuocTichID, CBODungChung.GetAllMasterCBOTableDM("DM_QUOCGIA"), "---Chọn---", new { @class = "form-control form-control-sm select2-single" })
    </div>
    <div class="form-group col-md-4">
        <label class="font-weight-bold">CCCD/Hộ chiếu <span class="text-danger font-weight-bold">(*)</span></label>
        @Html.TextBoxFor(model => model.SoCMND, new
        {
            @class = "form-control form-control-sm",
            @placeholder = "Nhập số CCCD/hộ chiếu",
            @data_rule_required = "true",
            @data_msg_required = "Vui lòng nhập số CCCD/hộ chiếu!!!",
            @data_rule_javascript = true,
            @data_msg_javascript = "Số CCCD/hộ chiếu không có đoạn Javascript không hợp lệ !!!",
            @data_rule_maHtml = true,
            @data_msg_maHtml = "Số CCCD/hộ chiếu không được chứa mã HTML!!!",
            @data_rule_maxlength = true,
            @data_value_maxlength = 30,
            @data_msg_maxlength = "Số CCCD/hộ chiếu không quá 30 ký tự!!!",
        })
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-4">
        <label class="font-weight-bold">Ngày cấp<span class="text-danger font-weight-bold">(*)</span></label>
        <div class="input-group">
            @Html.TextBoxFor(model => model.NgayCapCMND, new
            {
                @class = "form-control form-control-sm w-50 datepicker-share",
                @placeholder = "Nhập ngày cấp",
                @data_rule_required = "true",
                @data_msg_required = "Vui lòng nhập ngày cấp!!!"
            })
            <div class="input-group-prepend">
                <label for="" class="input-group-text cursor"><i class="far fa-calendar-alt "></i></label>
            </div>
        </div>
    </div>
    <div class="form-group col-md-4">
        <label class="font-weight-bold">Nơi cấp<span class="text-danger font-weight-bold">(*)</span></label>
        @Html.DropDownListFor(model => model.NoiCapID, CBODungChung.GetAllMasterCBOTableDM("DM_TINHTHANH"), "---Chọn---", new { @class = "form-control form-control-sm select2-single" })
    </div>
    <div class="form-group col-md-4">
        <label class="font-weight-bold">Địa chỉ </label>
        @Html.TextBoxFor(model => model.DiaChi, new
        {
            @class = "form-control form-control-sm",
            @placeholder = "Nhập địa chỉ",
            @data_rule_javascript = true,
            @data_msg_javascript = "Địa chỉ không có đoạn Javascript không hợp lệ !!!",
            @data_rule_maHtml = true,
            @data_msg_maHtml = "Địa chỉ không được chứa mã HTML!!!",
            @data_rule_maxlength = true,
            @data_value_maxlength = 200,
            @data_msg_maxlength = "Địa chỉ không quá 200 ký tự!!!",
        })
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-4">
        <label class="font-weight-bold">Bút danh/Nghệ danh</label>
        @Html.TextBoxFor(model => model.ButDanh, new
        {
            @class = "form-control form-control-sm",
            @placeholder = "Nhập bút danh",
            @data_rule_javascript = true,
            @data_msg_javascript = "Bút danh không có đoạn Javascript không hợp lệ !!!",
            @data_rule_maHtml = true,
            @data_msg_maHtml = "Bút danh không được chứa mã HTML!!!",
            @data_rule_maxlength = true,
            @data_value_maxlength = 100,
            @data_msg_maxlength = "Bút danh không quá 100 ký tự!!!",
        })
    </div>
</div>
<div class="text-right mt-2">
    <button class="btn btn-danger btn-sm text-white" type="button" id="btnCancelTacGia"><i class="fas fa-times mr-1"></i>Hủy </button>
    @if (admin == true || user.Right.Contains(CookieRight.TT_TacGia_InsUpd))
    {
        <button type="button" class="btn btn-success btn-block-sm btn-sm" id="btnSaveTacGia">
            <i class="far fa-save mr-1"></i> Lưu
        </button>
    }
</div>